Repository HelixDesignSystem/helix-ui, pull requests merged in 2018-11, with the labels that each got.

#364 surf-1415-fix-modal-positioning
  docs/_data/nav.json5
  docs/components/modals/index.html
  docs/components/modals/test.html
  docs/elements/hx-modal/index.html
  docs/elements/hx-modalbody/index.html
  docs/elements/hx-modalfoot/index.html
  docs/elements/hx-modalhead/index.html
  src/helix-ui/elements/HXModalElement.html
  src/helix-ui/elements/HXModalElement.less
  src/helix-ui/styles/elements/hx-modal.less
  src/helix-ui/styles/elements/hx-modalbody.less
  src/helix-ui/styles/elements/hx-modalfoot.less
  src/helix-ui/styles/elements/hx-modalhead.less
  src/helix-ui/styles/vars.less
Labels: :skull: Deprecation

#373 refactor(scripts): reorganize build scripts
  .eslintignore
  .gitignore
  .node-version
  bin/compile.js
  package.json
  plugins/rollup-plugin-less.js
  rollup.config.js
  scripts/_compile/index.js
  scripts/_config/index.js
  scripts/_generate/context.js
  scripts/_generate/index.js
  scripts/_generate/markup.js
  scripts/_generate/nunjucks.js
  scripts/_publish/publishDocs.js
  scripts/_util/copy.js
  scripts/_util/index.js
  scripts/build.js
  scripts/clean.js
  scripts/cleanPublic.js
  scripts/compile.js
  scripts/generate.js
  scripts/publish.js
  scripts/serve.js
  scripts/start.js
Labels: :tophat: hack-a-thon

#374 chore(wip): initialize functionality for careathon
  src/helix-ui/index.js
  src/helix-ui/index.spec.js
Labels: :tophat: hack-a-thon

#375 icons-into-json-file
  bin/buildIcons.js
  src/helix-ui/icons/icons.json
  src/helix-ui/icons/index.js
Labels: :tophat: hack-a-thon

#377 chore(build): buildAll
  .eslintignore
  .gitignore
  bin/buildIcons.js
  docs/_data/icons.json5
  docs/components/icons/index.html
  package.json
  scripts/_build/buildIcons.js
  scripts/_build/buildTemplates.js
  scripts/_build/index.js
  scripts/_generate/index.js
  scripts/build.js
  scripts/compile.js
  src/elements/templates.json
  src/helix-ui/icons/icons.json
  src/icons/angleBottom.svg
  src/icons/angleDown.svg
  src/icons/angleEnd.svg
  src/icons/angleLeft.svg
  src/icons/angleRight.svg
  src/icons/angleStart.svg
  src/icons/angleTop.svg
  src/icons/angleUp.svg
  src/icons/checkmarkCircle.svg
  src/icons/clock.svg
  src/icons/exclamationCircle.svg
  src/icons/exclamationDiamond.svg
  src/icons/exclamationTriangle.svg
  src/icons/externalLink.svg
  src/icons/helpCircle.svg
  src/icons/index.js
  src/icons/infoCircle.svg
  src/icons/input-time.svg
  src/icons/kbdArrowDown.svg
  src/icons/kbdArrowLeft.svg
  src/icons/kbdArrowRight.svg
  src/icons/kbdArrowUp.svg
  src/icons/kbdCapslock.svg
  src/icons/kbdCommand.svg
  src/icons/kbdDelete.svg
  src/icons/kbdEject.svg
  src/icons/kbdOption.svg
  src/icons/kbdReturn.svg
  src/icons/kbdShift.svg
  src/icons/kbdSpace.svg
  src/icons/kbdTab.svg
  src/icons/mimeArchive.svg
  src/icons/mimeAudio.svg
  src/icons/mimeCode.svg
  src/icons/mimeData.svg
  src/icons/mimeImage.svg
  src/icons/mimeSystem.svg
  src/icons/mimeText.svg
  src/icons/mimeVideo.svg
  src/icons/minusCircle.svg
  src/icons/plusOrMinus.svg
  src/icons/serverConfig.svg
  src/icons/serverIncident.svg
  src/icons/sortDown.svg
  src/icons/sortUp.svg
  src/icons/timesCircle.svg
Labels: :tophat: hack-a-thon

#387 fix(tabset): surf-1396 (issue #334) IE11 and Edge Tabs bug
  src/helix-ui/elements/HXTabsetElement.js
Labels: Bug: JavaScript
