Repository HelixDesignSystem/helix-ui, pull requests merged in 2018-07, with the labels that each got.

#270 refactor(polyfills): eliminate polyfill.io
  docs/_templates/partials/after_footer.njk
  docs/components/layouts/horizontal-layout-template.html
  docs/components/layouts/vertical-layout-template.html
  rollup.config.js
  src/browser-entry.js
  src/polyfills.js
  src/polyfills/ChildNode.js
  src/polyfills/Element.js
  src/polyfills/Object.js
Labels: #freefriday

#271 chore(linting): reconfigure eslint
  .eslintrc.json
  .eslintrc.prod.json
  .travis.yml
  package.json
Labels: #freefriday, :gear: pipeline

#272 docs(refactor): remove jquery
  docs/_templates/partials/after_footer.njk
  docs/components/icons/icon-demo.js
  docs/docs.js
  package.json
  yarn.lock
Labels: #freefriday, :memo: Documentation

#269 refactor(src-javascript): refactor js to current $ implementation
  src/helix-ui/elements/HXAccordionElement.js
  src/helix-ui/elements/HXAccordionPanelElement.js
  src/helix-ui/elements/HXAlertElement.js
  src/helix-ui/elements/HXBusyElement.js
  src/helix-ui/elements/HXCheckboxElement.js
  src/helix-ui/elements/HXDisclosureElement.js
  src/helix-ui/elements/HXElement.js
  src/helix-ui/elements/HXFileIconElement.js
  src/helix-ui/elements/HXIconElement.js
  src/helix-ui/elements/HXMenuElement.js
  src/helix-ui/elements/HXMenuitemElement.js
  src/helix-ui/elements/HXModalElement.js
  src/helix-ui/elements/HXPopoverElement.js
  src/helix-ui/elements/HXProgressElement.js
  src/helix-ui/elements/HXRevealElement.js
  src/helix-ui/elements/HXSearchAssistanceElement.js
  src/helix-ui/elements/HXSearchElement.js
  src/helix-ui/elements/HXTabElement.js
  src/helix-ui/elements/HXTabcontentElement.js
  src/helix-ui/elements/HXTablistElement.js
  src/helix-ui/elements/HXTabpanelElement.js
  src/helix-ui/elements/HXTabsetElement.js
  src/helix-ui/elements/HXToastElement.js
  src/helix-ui/elements/HXTooltipElement.js
  test/regression/generateRegressionTests.js.md
  test/regression/generateRegressionTests.js.snap
Labels: #freefriday

#278 Setup Netlify Deploy Previews
  netlify.toml
Labels: :construction_worker_man: Chore

#267 Remove all visreg code
  .travis.yml
  bin/start.js
  docs/components/checkboxes/test.html
  docs/components/search/test.html
  docs/components/typography/index.html
  docs/components/typography/test.html
  docs/elements/hx-progress/test.html
  test/.gitignore
  test/behavioral/behavioral.ts
  test/behavioral/chrome.ts
  test/behavioral/firefox.ts
  test/behavioral/tests/tabs.ts
  test/bin/util.ts
  test/bin/visreg.example.config.ts
  test/bin/visreg.ts
  test/common/util.ts
  test/dom-snapshots/README.md
  test/dom-snapshots/components-checkboxes-chrome.js.md
  test/dom-snapshots/components-checkboxes-chrome.js.snap
  test/dom-snapshots/components-checkboxes-firefox.js.md
  test/dom-snapshots/components-checkboxes-firefox.js.snap
  test/dom-snapshots/components-search-chrome.js.md
  test/dom-snapshots/components-search-chrome.js.snap
  test/dom-snapshots/components-search-firefox.js.md
  test/dom-snapshots/components-search-firefox.js.snap
  test/dom-snapshots/components-typography-chrome.js.md
  test/dom-snapshots/components-typography-chrome.js.snap
  test/dom-snapshots/components-typography-firefox.js.md
  test/dom-snapshots/components-typography-firefox.js.snap
  test/dom-snapshots/elements-hx-progress-chrome.js.md
  test/dom-snapshots/elements-hx-progress-chrome.js.snap
  test/dom-snapshots/elements-hx-progress-firefox.js.md
  test/dom-snapshots/elements-hx-progress-firefox.js.snap
  test/package.json
  test/regression/generateRegressionTests.js.md
  test/regression/generateRegressionTests.js.snap
  test/regression/generateRegressionTests.ts
  test/regression/generateSingleTest.js
  test/regression/regressionTestHandler.js
  test/regression/runSingleTest.ts
  test/scripts/regressionTest.sh
  test/scripts/run-travis-push-or-pr
  test/scripts/webdriver-update
  test/tsconfig.json
  test/visreg/chrome.ts
  test/visreg/firefox.ts
  test/visreg/screenshots/.keep
  test/visreg/visreg.ts
  test/yarn.lock
Labels: Wiki Update Required
