Repository HelixDesignSystem/helix-ui, pull requests merged in 2018-06, with the labels that each got.

#232 fix(styles): update shadowdom prefix styles with hx
  src/helix-ui/elements/HXAccordionPanelElement.html
  src/helix-ui/elements/HXAccordionPanelElement.js
  src/helix-ui/elements/HXAccordionPanelElement.less
  src/helix-ui/elements/HXAlertElement.html
  src/helix-ui/elements/HXAlertElement.js
  src/helix-ui/elements/HXAlertElement.less
  src/helix-ui/elements/HXCheckboxElement.html
  src/helix-ui/elements/HXCheckboxElement.js
  src/helix-ui/elements/HXCheckboxElement.less
  src/helix-ui/elements/HXErrorElement.html
  src/helix-ui/elements/HXErrorElement.less
  src/helix-ui/elements/HXFileIconElement.html
  src/helix-ui/elements/HXFileIconElement.js
  src/helix-ui/elements/HXFileIconElement.less
  src/helix-ui/elements/HXModalElement.html
  src/helix-ui/elements/HXModalElement.js
  src/helix-ui/elements/HXModalElement.less
  src/helix-ui/elements/HXPillElement.html
  src/helix-ui/elements/HXPillElement.js
  src/helix-ui/elements/HXPillElement.less
  src/helix-ui/elements/HXPopoverElement.html
  src/helix-ui/elements/HXPopoverElement.less
  src/helix-ui/elements/HXProgressElement.html
  src/helix-ui/elements/HXProgressElement.js
  src/helix-ui/elements/HXProgressElement.less
  src/helix-ui/elements/HXSearchElement.html
  src/helix-ui/elements/HXSearchElement.js
  src/helix-ui/elements/HXSearchElement.less
  src/helix-ui/elements/HXToastElement.html
  src/helix-ui/elements/HXToastElement.js
  src/helix-ui/elements/HXToastElement.less
  src/helix-ui/elements/HXTooltipElement.html
  src/helix-ui/elements/HXTooltipElement.less
  src/helix-ui/styles/elements/hx-accordion-panel.less
  test/regression/generateRegressionTests.js.md
  test/regression/generateRegressionTests.js.snap
Labels: PR: VIP, bug

#242 docs(Grid): fix responsive options table
  docs/components/grid/index.html
Labels: Documentation

#246 fix(HXElement): fix template caching (v0.9.x)
  src/helix-ui/elements/HXElement.js
  test/regression/generateRegressionTests.js.md
  test/regression/generateRegressionTests.js.snap
Labels: PR: VIP, bug

#247 fix(HXElement): fix template caching (v0.10.0)
  src/helix-ui/elements/HXElement.js
  test/regression/generateRegressionTests.js.md
  test/regression/generateRegressionTests.js.snap
Labels: DO NOT MERGE

#254 docs(downloads): modify getting started guide
  docs/_data/cdn.json5
  docs/_templates/guide.njk
  docs/_templates/partials/after_footer.njk
  docs/_templates/partials/head.njk
  docs/components/icons/icon-demo.js
  docs/components/icons/index.html
  docs/components/layouts/horizontal-layout-template.html
  docs/components/layouts/vertical-layout-template.html
  docs/docs.less
  docs/guides/getting-started/index.html
  lib/generate.js
  package.json
  src/helix-ui/styles/base/lists.less
  src/helix-ui/styles/components.less
  src/helix-ui/styles/components/buttons.less
  src/helix-ui/styles/components/panels.less
  src/helix-ui/styles/components/tabs.less
  yarn.lock
Labels: PR: VIP

#256 Fix Bugs / Update Buttons / Update Links
  docs/components/buttons/button-demo.js
  docs/components/buttons/index.html
  docs/components/buttons/test.html
  docs/components/modals/index.html
  docs/components/typography/index.html
  docs/styles/demo/button-docs.less
  src/helix-ui/elements/HXModalElement.js
  src/helix-ui/styles/base/links.less
  src/helix-ui/styles/components/buttons.less
  test/regression/generateRegressionTests.js.md
  test/regression/generateRegressionTests.js.snap
Labels: PR: VIP

#261 docs(minver): update minimum versions
  docs/components/badges/index.html
  docs/components/icons/index.html
  docs/components/lists/index.html
  docs/components/pills/index.html
  docs/components/progress/index.html
  docs/components/selector-strips/index.html
  docs/components/toasts/index.html
  docs/elements/hx-file-icon/index.html
  docs/elements/hx-pill/index.html
  docs/elements/hx-progress/index.html
  docs/elements/hx-toast/index.html
Labels: :memo: Documentation

#262 docs(download): add 3rd party dependency disclaimer
  docs/guides/getting-started/index.html
Labels: :memo: Documentation

#263 chore(github): Add Bug Report issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  docs/_templates/partials/global_nav.njk
  docs/docs.less
  src/helix-ui/styles/components/buttons.less
Labels: :construction_worker_man: Chore, :memo: Documentation

#265 Vis reg test suites for Text input component.
  docs/components/text-inputs/index.html
  test/common/util.ts
  test/visreg/visreg.ts
Labels: Bug: JavaScript
