Repository HelixDesignSystem/helix-ui, pull requests merged in 2018-08, with the labels that each got.

#296 chore(yarn): add install:clean script
  package.json
Labels: :construction_worker_man: Chore, :gear: pipeline

#311 fix(HXIcon): correct issues with HXIconElement
  docs/components/icons/index.html
  src/helix-ui/elements/HXAccordionPanelElement.less
  src/helix-ui/elements/HXAlertElement.html
  src/helix-ui/elements/HXAlertElement.less
  src/helix-ui/elements/HXCheckboxElement.less
  src/helix-ui/elements/HXErrorElement.html
  src/helix-ui/elements/HXErrorElement.less
  src/helix-ui/elements/HXFileIconElement.less
  src/helix-ui/elements/HXFileInputElement.less
  src/helix-ui/elements/HXFileTileElement.less
  src/helix-ui/elements/HXIconElement.html
  src/helix-ui/elements/HXIconElement.js
  src/helix-ui/elements/HXIconElement.less
  src/helix-ui/elements/HXModalElement.less
  src/helix-ui/elements/HXPillElement.html
  src/helix-ui/elements/HXPillElement.less
  src/helix-ui/elements/HXSearchElement.less
  src/helix-ui/elements/HXToastElement.less
  src/helix-ui/icons/key.svg
  src/helix-ui/icons/server-config.svg
  src/helix-ui/icons/server-incident.svg
  src/helix-ui/icons/server.svg
  src/helix-ui/styles/elements/hx-icon.less
  test/dom-snapshots/components-checkboxes-MicrosoftEdge.js.md
  test/dom-snapshots/components-checkboxes-MicrosoftEdge.js.snap
  test/dom-snapshots/components-checkboxes-firefox.js.md
  test/dom-snapshots/components-checkboxes-firefox.js.snap
  test/dom-snapshots/components-checkboxes-internet-explorer.js.md
  test/dom-snapshots/components-checkboxes-internet-explorer.js.snap
  test/dom-snapshots/components-search-MicrosoftEdge.js.md
  test/dom-snapshots/components-search-MicrosoftEdge.js.snap
  test/dom-snapshots/components-search-firefox.js.md
  test/dom-snapshots/components-search-firefox.js.snap
  test/dom-snapshots/components-search-internet-explorer.js.md
  test/dom-snapshots/components-search-internet-explorer.js.snap
  test/dom-snapshots/components-typography-MicrosoftEdge.js.md
  test/dom-snapshots/components-typography-MicrosoftEdge.js.snap
  test/dom-snapshots/components-typography-firefox.js.md
  test/dom-snapshots/components-typography-firefox.js.snap
  test/dom-snapshots/components-typography-internet-explorer.js.md
  test/dom-snapshots/components-typography-internet-explorer.js.snap
Labels: :skull: Deprecation

#309 refactor(*): refactor imports, exports, and jsdocs
  rollup.config.js
  src/COMPATIBILITY.md
  src/browser-entry.js
  src/helix-ui/elements.js
  src/helix-ui/elements/HXDisclosureElement.js
  src/helix-ui/elements/HXDivElement.js
  src/helix-ui/elements/HXElement.js
  src/helix-ui/elements/HXMenuElement.js
  src/helix-ui/elements/HXModalElement.js
  src/helix-ui/elements/HXPopoverElement.js
  src/helix-ui/elements/HXSearchAssistanceElement.js
  src/helix-ui/elements/HXTabpanelElement.js
  src/helix-ui/elements/HXTabsetElement.js
  src/helix-ui/elements/HXTooltipElement.js
  src/helix-ui/elements/index.js
  src/helix-ui/icons.js
  src/helix-ui/icons/index.js
  src/helix-ui/index.js
  src/helix-ui/util.js
  src/helix-ui/util/keys.js
  src/helix-ui/utils/index.js
  src/helix-ui/utils/position/index.js
  src/helix-ui/utils/position/offset.js
  src/node-entry.js
  src/polyfills/index.js
Labels: #freefriday, :rotating_light: Breaking Change

#319 fix(Box): correct bugs with Box
  docs/styles/demo/box-docs.less
  src/helix-ui/elements/index.js
Labels: PR: VIP

#321 docs(*): annotate usage inline and add react compatibility ref
  docs/elements/hx-busy/index.html
  docs/elements/hx-checkbox/index.html
  docs/elements/hx-pill/index.html
Labels: :memo: Documentation
