Repository HelixDesignSystem/helix-ui, pull requests merged in 2019-05, with the labels that each got.

#497 chore(tests): migrate Progress Bar tests
  docs/components/loader/index.html
  docs/components/loader/test-progress.html
Labels: :memo: Documentation

#502 feat(HXTabsetElement): improve support for dynamic tabs
  docs/components/tabset/index.html
  docs/components/tabset/tabset-demo.js
  docs/docs.js
  docs/docs.less
  docs/elements/hx-tabset/index.html
  src/helix-ui/elements/HXTabsetElement.js
  src/helix-ui/styles/components/buttons.less
  src/helix-ui/styles/overrides.less
Labels: :new: Feature, :sos: Patch

#504 feat(radio): add basic demo and enabled-focus-invalid tests
  docs/components/radio/index.html
  docs/components/radio/radio-basic-demo.js
  docs/components/radio/test.html
  docs/docs.js
Labels: :clipboard: Testing, :memo: Documentation
