Repository HelixDesignSystem/helix-ui, pull requests merged in 2019-09, with the labels that each got.

#569 Surf 1725 update entrypoints
  rollup.config.js
  scripts/_generate/index.js
  src/_bundle.umd.js
  src/browser-entry.js
Labels: :construction_worker_man: Chore, :gear: Pipeline

#571 chore(less): reorganize less components typography and breadcrumb
  scripts/_compile/index.js
  src/less/components.less
  src/less/components/breadcrumb/index.less
  src/less/components/popovers.less
  src/less/components/tables.less
  src/less/components/typography/index.less
  src/less/index.less
Labels: :construction_worker_man: Chore, :gear: Pipeline

#573 chore(less): reorganize less components phase 2
  docs/docs.less
  docs/styles/spec/radio-spec.less
  src/elements/hx-file-tile/_shadow.less
  src/less/components.less
  src/less/components/choice-tiles.less
  src/less/components/grid/index.less
  src/less/components/icon/index.less
  src/less/components/layout/index.less
  src/less/components/list/index.less
  src/less/components/loader/index.less
  src/less/components/menu/index.less
  src/less/components/modal/index.less
  src/less/components/navigation/index.less
  src/less/components/pagination/index.less
  src/less/components/panel/index.less
  src/less/components/pill/index.less
  src/less/components/popover/index.less
  src/less/components/radio/index.less
Labels: :construction_worker_man: Chore, :gear: Pipeline

#572 chore(less): reorganize less components phase 1
  docs/docs.less
  docs/styles/spec/button-spec.less
  docs/styles/spec/checkbox-spec.less
  docs/styles/spec/choice-tile-spec.less
  docs/styles/spec/dropdown-select-spec.less
  docs/styles/spec/file-input-spec.less
  docs/styles/spec/text-input-spec.less
  docs/styles/spec/textarea-spec.less
  src/elements/hx-drawer/_shadow.less
  src/elements/hx-file-tile/_shadow.less
  src/elements/hx-modal/_shadow.less
  src/elements/hx-pill/_shadow.less
  src/elements/hx-toast/_shadow.less
  src/less/components.less
  src/less/components/accordion/index.less
  src/less/components/accordion/stepper.less
  src/less/components/alert/index.less
  src/less/components/badge/index.less
  src/less/components/box/index.less
  src/less/components/button/index.less
  src/less/components/checkbox/index.less
  src/less/components/choice-tile/index.less
  src/less/components/drawer/index.less
  src/less/components/dropdown-select/SelectControl.less
  src/less/components/dropdown-select/SelectFacade.less
  src/less/components/dropdown-select/index.less
  src/less/components/file/hx-file-control.less
  src/less/components/file/index.less
  src/less/components/form/FieldName.less
  src/less/components/form/TextControl.less
  src/less/components/form/_hxTextCtrl-DEPRECATED.less
  src/less/components/form/index.less
  src/less/components/layout/index.less
  src/less/components/menu/index.less
  src/less/components/radio/index.less
  src/less/components/text-input/index.less
  src/less/components/textarea/index.less
Labels: :construction_worker_man: Chore, :gear: Pipeline

#574 chore(less): reorganize less components phase 3
  src/less/components.less
  src/less/components/reveal/index.less
  src/less/components/search/index.less
  src/less/components/selector-strip/index.less
  src/less/components/table/index.less
  src/less/components/tabset/index.less
  src/less/components/toast/index.less
  src/less/components/tooltip/index.less
Labels: :construction_worker_man: Chore, :gear: Pipeline

#575 chore(pipeline): support SASS alongside LESS
  docs/components/_index.scss
  docs/components/index.js
  docs/index.scss
  package.json
  rollup-utils/rollup-plugin-less.js
  rollup-utils/rollup-plugin-sass.js
  rollup.config.js
  scripts/_compile/index.js
  scripts/_config/index.js
  scripts/_generate/index.js
  scripts/start.js
  src/elements/_base.scss
  src/elements/hx-accordion-panel/_shadow.scss
  src/elements/hx-accordion-panel/index.js
  src/elements/hx-error/_shadow.scss
  src/elements/hx-error/index.js
  src/less/base/links.less
  src/less/components.less
  src/less/components/popover/index.less
  src/less/components/table/index.less
  src/less/index.less
  src/scss/_config.scss
  src/scss/_overrides.scss
  src/scss/_vars.scss
  src/scss/base/_index.scss
  src/scss/base/_links.scss
  src/scss/base/_typography.scss
  src/scss/components/_index.scss
  src/scss/components/accordion/_index.scss
  src/scss/components/accordion/_stepper.scss
  src/scss/components/typography/_hljs.scss
  src/scss/components/typography/_index.scss
  src/scss/helpers/_alignment.scss
  src/scss/helpers/_index.scss
  src/scss/helpers/_wrapping.scss
  src/scss/index.scss
  src/scss/mixins/_index.scss
  src/scss/reset/_html5.scss
  src/scss/reset/_index.scss
  yarn.lock
Labels: :construction_worker_man: Chore, :gear: Pipeline

#576 chore(yarn): patch dev dependencies
  package.json
  yarn.lock
Labels: :construction_worker_man: Chore

#578 refactor(hx-file-tile): convert from LESS to SASS
  docs/components/_index.scss
  docs/components/typography/_index.scss
  docs/docs.less
  src/elements/hx-file-tile/_shadow.scss
  src/elements/hx-file-tile/index.js
  src/less/base/links.less
  src/less/components.less
  src/scss/base/_links.scss
  src/scss/components/_index.scss
  src/scss/components/button/_index.scss
  src/scss/components/button/_mixins.scss
  src/scss/components/loader/_hx-busy.scss
  src/scss/components/loader/_hx-progress.scss
  src/scss/components/loader/_index.scss
Labels: :construction_worker_man: Chore

#582 chore(SASS): convert LESS mixins to SASS
  src/less/components.less
  src/less/mixins.less
  src/less/mixins/microsoft.less
  src/less/mixins/mozilla.less
  src/less/mixins/standard.less
  src/less/mixins/webkit.less
  src/scss/components/_index.scss
  src/scss/components/accordion/_stepper.scss
  src/scss/components/dropdown-select/_mixins.scss
  src/scss/components/form/_mixins.scss
  src/scss/components/form/mixins/_input.scss
  src/scss/components/form/mixins/_placeholder.scss
  src/scss/components/selector-strip/_index.scss
  src/scss/components/typography/_hljs.scss
  src/scss/components/typography/_index.scss
  src/scss/mixins/_focus.scss
  src/scss/mixins/_index.scss
  src/scss/mixins/_microsoft.scss
  src/scss/mixins/_mozilla.scss
  src/scss/mixins/_standard.scss
  src/scss/mixins/_traits.scss
  src/scss/mixins/_webkit.scss
  src/scss/reset/_html5.scss
Labels: :construction_worker_man: Chore, :gear: Pipeline

#586 SURF-1874 Changes
  src/less/components.less
  src/scss/components/_index.scss
  src/scss/components/alert/index.scss
Labels: :gear: Pipeline, CSS

#587 refactor(SCSS): refactor Button mixins to support Shadow DOM use
  src/elements/hx-file-tile/_shadow.scss
  src/less/components/button/index.less
  src/scss/components/button/_mixins.scss
Labels: :gear: Pipeline, CSS

#588 refactor(styles): deprecate box LESS mixins for SCSS mixins
  src/less/components/box/index.less
  src/scss/components/_index.scss
  src/scss/components/box/_index.scss
  src/scss/components/box/_mixins.scss
Labels: :gear: Pipeline, CSS

#590 SURF-1875 Changes
  src/less/components.less
  src/scss/components/_index.scss
  src/scss/components/badge/index.scss
Labels: CSS

#591 SURF-1876 Changes
  src/less/components.less
  src/scss/components/_index.scss
  src/scss/components/breadcrumb/index.scss
Labels: CSS

#593 chore(pipeline): tweak watch globs
  scripts/start.js
Labels: :construction_worker_man: Chore, :gear: Pipeline

#589 refactor(mixins): copy Form-related mixins to SCSS
  src/less/components/form/FieldName.less
  src/less/components/form/TextControl.less
  src/less/components/form/index.less
  src/less/mixins.less
  src/less/mixins/microsoft.less
  src/less/mixins/mozilla.less
  src/less/mixins/standard.less
  src/less/mixins/webkit.less
  src/scss/_config.scss
  src/scss/_mixins.scss
  src/scss/_overrides.scss
  src/scss/base/_index.scss
  src/scss/components/_index.scss
  src/scss/components/dropdown-select/_mixins.scss
  src/scss/components/form/_mixins.scss
  src/scss/components/form/mixins/_fieldName.scss
  src/scss/components/form/mixins/_helpText.scss
  src/scss/components/form/mixins/_input.scss
  src/scss/components/form/mixins/_placeholder.scss
  src/scss/components/form/mixins/_textControl.scss
  src/scss/components/selector-strip/_index.scss
  src/scss/components/typography/_index.scss
  src/scss/helpers/_index.scss
  src/scss/index.scss
  src/scss/mixins/_focus.scss
  src/scss/mixins/_index.scss
  src/scss/mixins/_microsoft.scss
  src/scss/mixins/_mozilla.scss
  src/scss/mixins/_standard.scss
  src/scss/mixins/_traits.scss
  src/scss/mixins/_webkit.scss
  src/scss/reset/_index.scss
Labels: :gear: Pipeline, CSS

#594 SURF-1878 Changes
  src/less/components.less
  src/scss/components/_index.scss
  src/scss/components/icon/index.scss
Labels: CSS

#596 SURF-1879 Changes
  src/less/components/loader/index.less
Labels: CSS

#597 refactor(src): deprecate .hxComponent in LESS
  src/less/components.less
  src/scss/components/_config.scss
  src/scss/components/_index.scss
  src/scss/components/tooltip/_index.scss
Labels: CSS

#598 refactor(SCSS): deprecate Grid LESS mixins
  docs/_example.scss
  docs/components/_index.scss
  docs/components/grid/_index.scss
  docs/docs.less
  docs/index.scss
  docs/styles/demo/grid-docs.less
  src/elements/hx-drawer/_shadow.scss
  src/less/components.less
  src/less/components/grid/index.less
  src/scss/_vars.scss
  src/scss/components/_index.scss
  src/scss/components/grid/_config.scss
  src/scss/components/grid/_index.scss
Labels: CSS
