Repository HelixDesignSystem/helix-ui, pull requests merged in 2019-01, with the labels that each got.

#412 fix(*): Compatibility Updates
  docs/_data/polyfilled-apis.json5
  docs/_positions.js
  docs/_templates/partials/app_nav.njk
  docs/_templates/props/Positionable/optimumPosition.njk
  docs/_templates/props/Positionable/relativeElement.njk
  docs/_templates/props/Positionable/relativeTo.njk
  docs/_templates/props/Revealable/open.njk
  docs/components/popovers/test.html
  docs/components/tooltips/test.html
  docs/components/tooltips/tooltip-demo.js
  docs/elements/hx-menu/index.html
  docs/elements/hx-popover/index.html
  docs/elements/hx-search-assistance/index.html
  docs/elements/hx-tooltip/index.html
  src/helix-ui/elements/HXAccordionElement.js
  src/helix-ui/elements/HXDisclosureElement.js
  src/helix-ui/elements/HXDivElement.js
  src/helix-ui/elements/HXDropFenceElement.js
  src/helix-ui/elements/HXElement.js
  src/helix-ui/elements/HXErrorElement.js
  src/helix-ui/elements/HXFileIconElement.js
  src/helix-ui/elements/HXIconElement.js
  src/helix-ui/elements/HXModalElement.js
  src/helix-ui/elements/HXPopoverElement.js
  src/helix-ui/elements/HXSearchElement.js
  src/helix-ui/elements/HXTabpanelElement.js
  src/helix-ui/elements/HXTabsetElement.js
  src/helix-ui/elements/HXTooltipElement.js
  src/helix-ui/elements/_positioning.less
  src/helix-ui/mixins/Positionable.js
  src/helix-ui/styles/components/search.less
  src/helix-ui/styles/elements/hx-menu.less
  src/helix-ui/styles/elements/hx-popover.less
  src/helix-ui/styles/elements/hx-search-assistance.less
  src/helix-ui/styles/elements/hx-tooltip.less
  src/helix-ui/styles/mixins.less
  src/helix-ui/utils/alignment.js
  src/helix-ui/utils/index.js
  src/helix-ui/utils/offset.js
  src/helix-ui/utils/position/index.js
Labels: PR: VIP

#435 fix(Positionable): correct support for HTML5 IDs
  docs/components/popovers/test.html
  docs/components/tooltips/test.html
  src/helix-ui/elements/HXDisclosureElement.js
  src/helix-ui/elements/HXTooltipElement.js
  src/helix-ui/mixins/Positionable.js
Labels: Bug: JavaScript

#434 [issue 394] chore(tables): surf-1546 table css resets
  src/helix-ui/styles/helpers/alignment.less
Labels: :rotating_light: Breaking Change, Bug: CSS
