Repository HelixDesignSystem/helix-ui, pull requests merged in 2019-11, with the labels that each got.

#629 refactor(popover): convert Light DOM LESS to SCSS
  docs/components/_index.scss
  docs/components/popover/_spec.scss
  docs/docs.less
  src/less/components.less
  src/scss/components/_index.scss
  src/scss/components/popover/_index.scss
Labels: CSS

#630 feat(pipeline)!: add support for webpack import
  .babelrc
  .eslintrc.prod.json
  .travis.yml
  LICENSE
  docs/_templates/application.njk
  docs/docs.js
  gulpfile.esm.js
  package.json
  rollup-utils/rollup-plugin-less.js
  rollup.config.js
  scripts/_compile/index.js
  scripts/_generate/index.js
  scripts/compile.js
  scripts/generate.js
  scripts/serve.js
  scripts/start.js
  src/_bundle.es5.js
  src/_bundle.es6.js
  src/_bundle.umd.js
  src/index.js
  src/utils/alignment/index.js
  src/utils/index.js
  src/utils/offset/index.js
  tasks/bundle/browser.js
  tasks/bundle/index.js
  tasks/bundle/module.js
  tasks/bundle/styles.js
  tasks/config.js
  tasks/rollup/index.js
  tasks/rollup/plugin-sass.js
  tasks/rollup/plugins.js
  yarn.lock
Labels: :new: Feature, :rotating_light: Breaking Change, PR: VIP

#625 refactor(Radio): convert Light DOM LESS to SCSS
  src/less/components.less
  src/scss/components/_index.scss
  src/scss/components/radio/_index.scss
Labels: :memo: Documentation, CSS

#632 refactor(text-input): SURF-1900
  docs/components/_index.scss
  docs/components/text-input/_spec.scss
  docs/docs.less
  src/less/components.less
  src/less/components/text-input/index.less
  src/scss/components/_index.scss
  src/scss/components/text-input/_index.scss
Labels: :memo: Documentation, CSS

#633 refactor(textarea): convert Light DOM LESS to SCSS
  docs/components/_index.scss
  docs/components/textarea/_spec.scss
  docs/docs.less
  docs/styles/spec/textarea-spec.less
  src/less/components.less
  src/scss/components/_index.scss
  src/scss/components/textarea/_index.scss
Labels: :memo: Documentation, CSS

#640 [0.14.x] fix(initialize): remove wcr handler after first run
  src/helix-ui/index.js
Labels: :sos: Patch, PR: VIP

#639 [0.15.x] fix(initialize): remove wcr handler after first run
  src/helix-ui/index.js
Labels: :sos: Patch, PR: VIP

#638 [0.16.x] fix(initialize): remove wcr handler after first run
  src/helix-ui/index.js
Labels: :sos: Patch, PR: VIP

#637 [0.17.x] fix(initialize): remove wcr handler after first run
  src/helix-ui/index.js
Labels: :sos: Patch, PR: VIP

#641 [0.18.x] fix(onWebComponentsReady): remove wcr handler after first run
  src/utils/index.js
Labels: :sos: Patch
