Repository HelixDesignSystem/helix-ui, pull requests merged in 2019-07, with the labels that each got.

#522 docs(CSS): adjust scope of `max-width` on `<p>`
  docs/docs.less
Labels: :memo: Documentation

#521 fix(radios): add missing demo page <hx-radio-set> elements
  docs/components/box/index.html
  docs/components/button/index.html
  docs/components/file/index.html
  docs/components/modal/index.html
  docs/components/table/index.html
  src/helix-ui/styles/components/radios.less
Labels: #freefriday

#524 chore(yarn): upgrade various dev dependencies
  yarn.lock
Labels: :construction_worker_man: Chore, :gear: Pipeline
