Repository HelixDesignSystem/helix-ui, pull requests merged in 2020-09, with the labels that each got.

#757 docs(hx-switch): Switch documentation
  docs/_data/nav.json5
  docs/components/switch/error-switch-demo.js
  docs/components/switch/index.html
  docs/components/switch/switch-demo.js
  docs/elements/hx-switch-control/index.html
  docs/elements/hx-switch/index.html
  src/elements/hx-switch-control/index.js
  src/elements/hx-switch/index.js
  src/scss/components/switch/_index.scss
Labels: :memo: Documentation, :new: :tada: HelixUI Component

#759 test(hx-tooltip): implement component tests
  src/elements/hx-tooltip/index.spec.js
Labels: :clipboard: Testing

#763 test(stepper): implement component tests
  src/elements/hx-accordion/index.spec.js
Labels: :clipboard: Testing

#749 feat(hx-toggle): implement toggle component
  docs/_data/nav.json5
  docs/components/toggle/_spec.scss
  docs/components/toggle/index.html
  docs/components/toggle/test.html
  docs/components/toggle/toggle-demo.js
  docs/docs.js
  docs/elements/hx-toggle-control/index.html
  docs/elements/hx-toggle/index.html
  src/elements/hx-toggle-control/index.js
  src/elements/hx-toggle-control/index.spec.js
  src/elements/hx-toggle/_shadow.html
  src/elements/hx-toggle/_shadow.scss
  src/elements/hx-toggle/index.js
  src/elements/hx-toggle/index.spec.js
  src/elements/index.js
  src/scss/components/_index.scss
  src/scss/components/toggle/_config.scss
  src/scss/components/toggle/_index.scss
  src/scss/components/toggle/mixins/_hxToggleControl.scss
Labels: :clipboard: Testing, :new: :tada: HelixUI Component

#765 publish(npm): v1.0.0 [skip ci]
  package.json
Labels: Milestone
