Repository HelixDesignSystem/helix-ui, pull requests merged in 2020-05, with the labels that each got.

#683 test(hx-error): unit test cases surf2006
  src/elements/hx-error/index.spec.js
Labels: :clipboard: Testing, PR: Comments Provided

#685 test(hx-busy): restructure and add additional tests
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  karma-init.js
  src/elements/hx-busy/index.js
  src/elements/hx-busy/index.spec.js
Labels: :clipboard: Testing

#687 test(ui): implement automated browser testing
  .travis.yml
  karma-sauce-init.js
  karma.sauce.config.js
  package.json
  src/elements/hx-error/index.spec.js
Labels: :clipboard: Testing, :gear: Pipeline, Milestone

#686 test(hx-alert): restructure and add more tests
  src/elements/hx-alert/index.spec.js
Labels: :clipboard: Testing

#684 test(hx-progress): unit test cases surf2017
  src/elements/hx-progress/index.spec.js
Labels: :clipboard: Testing

#693 chore(travis): update config
  .travis.yml
Labels: :clipboard: Testing, :gear: Pipeline

#694 chore(travis): update config for build from a fork
  .travis.yml
Labels: :clipboard: Testing

#695 chore(travis): update config for builds from a fork
  .travis.yml
Labels: :clipboard: Testing, :gear: Pipeline

#696 perf(travis): migrate to travis-ci.com infrastructure
  README.md
Labels: :gear: Pipeline, Milestone

#688 test(hx-file-control): surf-2007
  src/elements/hx-file-control/index.spec.js
Labels: :clipboard: Testing

#691 test(hx-file-icon): surf-2008
  src/elements/hx-file-icon/index.spec.js
Labels: :clipboard: Testing

#690 test(hx-div): surf2002
  src/elements/hx-div/index.js
  src/elements/hx-div/index.spec.js
Labels: :clipboard: Testing

#697 test(hx-file-input): surf-2009
  src/elements/hx-file-input/index.spec.js
Labels: :clipboard: Testing

#698 publish(npm): v0.22.0 [skip ci]
  package.json
Labels: :new: Feature, Milestone
