Repository HelixDesignSystem/helix-ui, pull requests merged in 2020-06, with the labels that each got.

#702 test(hx-select): surf-2024
  src/elements/hx-select/index.spec.js
Labels: :clipboard: Testing

#700 test(hx-search): surf-2021
  src/elements/hx-search/index.spec.js
Labels: :clipboard: Testing

#699 test(hx-pill test cases): surf2015
  src/elements/hx-pill/index.spec.js
Labels: :clipboard: Testing

#706 test(hx-menu): surf-2012
  src/elements/hx-menu/index.spec.js
Labels: :clipboard: Testing

#703 test(hx-modal): surf2014
  src/elements/hx-modal/index.spec.js
Labels: :clipboard: Testing

#704 test(hx-disclosure): add component tests and sauce builds
  karma.sauce.config.js
  src/elements/hx-disclosure/index.spec.js
Labels: :clipboard: Testing, :gear: Pipeline

#708 test(hx-menuitem test cases): surf2013
  src/elements/hx-menuitem/index.spec.js
Labels: :clipboard: Testing

#705 test(hx-file-tile): surf-2010
  src/elements/hx-file-tile/index.spec.js
Labels: :clipboard: Testing

#711 feat(hx-beacon): implement beacon with component tests
  docs/_data/nav.json5
  docs/components/beacon/beacon-demo.js
  docs/components/beacon/index.html
  docs/components/toast/index.html
  docs/docs.js
  docs/elements/hx-beacon/index.html
  src/elements/hx-beacon/_shadow.html
  src/elements/hx-beacon/_shadow.scss
  src/elements/hx-beacon/index.js
  src/elements/hx-beacon/index.spec.js
  src/elements/hx-div/index.js
  src/elements/index.js
  src/scss/components/_index.scss
  src/scss/components/beacon/index.scss
Labels: :clipboard: Testing, :new: Feature

#713 test(hx-icon): implement component tests
  src/elements/hx-icon/index.spec.js
Labels: :clipboard: Testing

#718 publish(npm): v0.23.0 [skip ci]
  package.json
Labels: :new: Feature, Milestone
