Repository HelixDesignSystem/helix-ui, pull requests merged in 2020-07, with the labels that each got.

#720 test(hx-reveal): test cases SURF 2061
  src/elements/hx-reveal/index.spec.js
Labels: :clipboard: Testing

#722 test(hx-radio-control): test cases SURF2019
  src/elements/hx-radio-control/index.spec.js
Labels: :clipboard: Testing

#715 feat(hx-search-control): add event listener and component tests
  src/elements/hx-search-control/index.js
  src/elements/hx-search-control/index.spec.js
Labels: :clipboard: Testing, JavaScript

#714 test(hx-select-control): surf-2025
  src/elements/hx-select-control/index.spec.js
Labels: :clipboard: Testing

#723 test(hx-password-control): component tests surf-2056
  src/elements/hx-password-control/index.spec.js
Labels: :clipboard: Testing

#716 test(hx-popover): component tests surf2016
  src/elements/hx-popover/index.js
  src/elements/hx-popover/index.spec.js
Labels: :clipboard: Testing

#725 test(hx-radio): test cases
  src/elements/hx-radio/index.spec.js
Labels: :clipboard: Testing

#728 test(hx-email-control): test cases
  docs/components/email/email-control-demo.js
  src/elements/hx-email-control/index.spec.js
Labels: :clipboard: Testing

#740 test(deprecate): deprecate old testing framework
  test/package.json.deprecated
  test/yarn.lock.deprecated
Labels: :clipboard: Testing, :construction: Deprecation

#709 test(hx-tab): implement component tests surf-2026
  src/elements/hx-tab/index.spec.js
Labels: :clipboard: Testing

#730 test(hx-accordian): implement component tests
  src/elements/hx-accordion/index.spec.js
Labels: :clipboard: Testing

#729 test(hx-toast): implement component tests
  src/elements/hx-toast/index.spec.js
Labels: :clipboard: Testing

#721 docs(faq): fix typo
  docs/guides/faq/index.html
Labels: :memo: Documentation

#732 test(hx-tablist): implement component tests
  src/elements/hx-tablist/index.spec.js
Labels: :clipboard: Testing

#733 test(hx-tabpanel): implement component tests
  src/elements/hx-tabpanel/index.spec.js
Labels: :clipboard: Testing

#710 test(hx-tabcontent): implement component tests
  src/elements/hx-tabcontent/index.spec.js
Labels: :clipboard: Testing

#731 test(hx-accordion-panel): implement component tests
  src/elements/hx-accordion-panel/index.spec.js
Labels: :clipboard: Testing

#742 test(hx-tabset): implement component tests
  src/elements/hx-tabset/index.spec.js
Labels: :clipboard: Testing

#707 feat(hx-switch): implement switch component
  docs/_data/nav.json5
  docs/components/switch/_spec.scss
  docs/components/switch/error-switch-demo.js
  docs/components/switch/index.html
  docs/components/switch/switch-demo.js
  docs/components/switch/test.html
  docs/docs.js
  docs/elements/hx-switch/index.html
  src/elements/hx-switch-control/index.js
  src/elements/hx-switch-control/index.spec.js
  src/elements/hx-switch/_shadow.html
  src/elements/hx-switch/_shadow.scss
  src/elements/hx-switch/index.js
  src/elements/hx-switch/index.spec.js
  src/elements/index.js
  src/scss/components/_index.scss
  src/scss/components/switch/_config.scss
  src/scss/components/switch/_index.scss
  src/scss/components/switch/mixins/_hxSwitchControl.scss
Labels: :new: :construction: BETA FEATURE

#743 fix(tabset): dynamic tabs bug fixes Issue #516
  src/elements/hx-tab/index.spec.js
  src/elements/hx-tabcontent/index.spec.js
  src/elements/hx-tablist/index.spec.js
  src/elements/hx-tabpanel/index.spec.js
  src/elements/hx-tabset/index.js
  src/elements/hx-tabset/index.spec.js
Labels: :clipboard: Testing, BUG FIX, JavaScript

#744 publish(npm): v0.24.0 [skip ci]
  package.json
Labels: Milestone
