Repository HelixDesignSystem/helix-ui, pull requests merged in 2020-12, with the labels that each got.

#784 feat(topnav): design feedback for top navigation component
  docs/components/topnav/test.html
  src/scss/components/topnav/index.scss
Labels: CSS

#785 feat(secnav): design review for secondary navigation component
  docs/components/secnav/index.html
  docs/components/secnav/secnav-demo.js
  docs/components/secnav/test.html
  src/scss/components/secnav/index.scss
Labels: CSS, PR: Needs Design Review

#796 publish(npm): v1.2.0 [skip ci]
  package.json
Labels: Milestone

#800 feat(v1.x): HelixUI-v1.x documentation
  README.md
  docs/index.html
Labels: :memo: Documentation, :new: FEATURE

#804 publish(npm): v2.0.0-rc.0
  package.json
Labels: Milestone

#793 docs(hx-breadcrumb): implement and document vars and attrs
  src/scss/components/breadcrumb/index.scss
Labels: :memo: Documentation, CSS

#790 docs(accordion): implement and document vars and attrs
  src/scss/components/accordion/_stepper.scss
Labels: :memo: Documentation, CSS

#794 docs(drawer): implement and document attrs and vars
  src/scss/components/drawer/_index.scss
Labels: :memo: Documentation, CSS

#806 feat(colors): update color palette
  src/scss/_vars.scss
Labels: CSS

#805 docs(list): implement and document vars and attrs
  src/scss/components/list/_index.scss
Labels: :memo: Documentation, CSS

#808 feat(radio): new color palette specs
  src/scss/components/radio/_index.scss
  src/scss/components/radio/mixins/_hxRadioControl.scss
  src/scss/components/radio/mixins/_hxRadioFacade.scss
Labels: CSS

#811 refactor(textinput): update component specs
  src/scss/components/form/mixins/_fieldName.scss
  src/scss/components/form/mixins/_helpText.scss
  src/scss/components/form/mixins/_textControl.scss
  src/scss/components/text-input/_index.scss
Labels: :new: New Component Specs

#807 refactor(topnav): update top navigation component specs
  docs/components/topnav/index.html
  docs/components/topnav/test.html
  docs/components/topnav/topnav-demo.js
  src/scss/components/topnav/index.scss
Labels: :new: New Component Specs

#810 refactor(secnav): update secondary navigation component specs
  docs/components/secnav/index.html
  docs/components/secnav/secnav-demo.js
  docs/components/secnav/test.html
  src/scss/components/secnav/index.scss
Labels: :new: New Component Specs

#813 feat(breadcrumb): update component specs
  src/scss/components/breadcrumb/index.scss
Labels: :new: New Component Specs

#812 feat(checkbox): update component specs
  src/scss/components/checkbox/_index.scss
  src/scss/components/checkbox/mixins/_hxCheckboxControl.scss
  src/scss/components/checkbox/mixins/_hxCheckboxFacade.scss
  src/scss/components/radio/mixins/_hxRadioControl.scss
  src/scss/components/radio/mixins/_hxRadioFacade.scss
Labels: :new: New Component Specs

#801 docs(email): implement and document vars and attrs
  src/scss/components/email/_index.scss
Labels: :memo: Documentation, CSS

#815 refactor(email): update component specs
  src/scss/components/email/_index.scss
Labels: :new: New Component Specs

#816 refactor(password): update component specs
  src/scss/components/password-input/_index.scss
Labels: :new: New Component Specs

#817 publish(npm): v2.0.0-rc.1
  package.json
Labels: Milestone
