Repository HelixDesignSystem/helix-ui, pull requests merged in 2020-08, with the labels that each got.

#745 test(hx-tabset): add dynamic tab with id on render
  src/elements/hx-tabset/index.spec.js
Labels: :clipboard: Testing

#746 test(hx-drop-fence): implement component tests
  src/elements/hx-drop-fence/index.spec.js
Labels: :clipboard: Testing

#747 test(hx-checkbox): implement component tests
  src/elements/hx-checkbox/index.spec.js
Labels: :clipboard: Testing

#748 test(hx-checkbox-control): implement component tests
  src/elements/hx-checkbox-control/index.spec.js
Labels: :clipboard: Testing

#750 test(hx-text-control): implement component tests
  src/elements/hx-text-control/index.spec.js
Labels: :clipboard: Testing

#751 test(hx-textarea-control): implement component tests
  src/elements/hx-textarea-control/index.spec.js
Labels: :clipboard: Testing

#756 test(hx-drawer): implement component tests
  src/elements/hx-drawer/index.spec.js
Labels: :clipboard: Testing

#755 feat(icons): adds fish-hook icon for O365 team
  docs/_data/icons.json5
  src/images/icons/fish-hook.svg
  src/utils/icons/index.js
Labels: Feature Request

#754 test(hx-drop-zone): implement component tests
  src/elements/hx-drop-zone/index.spec.js
Labels: :clipboard: Testing

#752 test(hx-checkbox-set): implement component tests
  src/elements/hx-checkbox-set/index.spec.js
Labels: :clipboard: Testing

#753 test(hx-radio-set): implement component tests
  src/elements/hx-radio-set/index.spec.js
Labels: :clipboard: Testing, PR: Comments Provided
