Repository HelixDesignSystem/helix-ui, pull requests merged in 2020-04, with the labels that each got.

#676 feat(testing): implement component testing framework
  .gitignore
  .travis.yml
  karma.conf.js
  package.json
  src/elements/hx-alert/index.spec.js
  src/elements/hx-busy/index.spec.js
  yarn.lock
Labels: :clipboard: Testing

#675 refactor(stepper content): surf1307
  docs/_data/nav.json5
  docs/components/accordion/index.html
  docs/components/stepper/index.html
  src/elements/hx-accordion-panel/_shadow.scss
  src/scss/components/accordion/_stepper.scss
Labels: :new: Feature

#679 fix(travis): update config
  .travis.yml
Labels: :construction_worker_man: Chore

#673 refactor(button): tertiary button padding
  docs/components/button/button-demo.js
  docs/components/button/index.html
  src/scss/components/button/mixins/_hxButton.scss
Labels: :construction: Deprecation

#681 Initialize Karma With Helix
  karma-init.js
  karma.conf.js
  src/elements/hx-alert/index.spec.js
  src/elements/hx-busy/index.spec.js
Labels: :clipboard: Testing, :gear: Pipeline
