Repository HelixDesignSystem/helix-ui, pull requests merged in 2021-01, with the labels that each got.

#819 feat(tabset): new component specs
  src/scss/components/tabset/_index.scss
Labels: :new: New Component Specs

#822 chore(releases): update component specs based on feedback
  docs/_data/nav.json5
  src/scss/base/_typography.scss
  src/scss/components/checkbox/_index.scss
  src/scss/components/pill/_index.scss
  src/scss/components/radio/_index.scss
Labels: :new: New Component Specs

#821 feat(button): new component specs
  src/scss/components/button/mixins/_hxButton.scss
  src/scss/components/popover/_index.scss
Labels: :new: New Component Specs

#823 feat(icons): implement and update icon specs
  docs/_data/icons.json5
  docs/components/icon/index.html
  src/images/icons/account.svg
  src/images/icons/bell.svg
  src/images/icons/billing.svg
  src/images/icons/critical.svg
  src/images/icons/information.svg
  src/images/icons/ok.svg
  src/images/icons/pending.svg
  src/images/icons/support.svg
  src/images/icons/ticketing.svg
  src/images/icons/unavailable.svg
  src/images/icons/user.svg
  src/images/icons/warning.svg
  src/utils/icons/index.js
Labels: :new: New Component Specs

#814 feat(choice tile): new component specs
  docs/components/icon/index.html
  src/scss/components/choice-tile/_index.scss
  src/scss/components/choice-tile/mixins/_hxChoiceTile.scss
Labels: :new: New Component Specs

#824 publish(npm): v2.0.0
  package.json
Labels: Milestone

#798 docs(checkbox): implement and document vars and attrs
  src/scss/components/checkbox/_index.scss
  src/scss/components/checkbox/mixins/_hxCheckboxControl.scss
  src/scss/components/checkbox/mixins/_hxCheckboxFacade.scss
Labels: :memo: Documentation, CSS
